apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-registry
  namespace: sodalite-services
spec:
  selector:
    matchLabels:
      app: grafana-registry
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana-registry
    spec:
      containers:
      - image: sodaliteh2020/grafana-registry
        name: grafana-registry
        env:
        - name: GF_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana
              key: admin-user
        - name: GF_ADMIN_PW
          valueFrom:
            secretKeyRef:
              name: grafana
              key: admin-pw
        - name: GF_PORT
          value: 80
        - name: GF_REGISTRY_GUNICORN_WORKERS
          value: "4"
        - name: OIDC_INTROSPECTION_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: introspect-url
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: client-secret
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: client-id
        - name: PROMETHEUS_ADDRESS
          value: prometheus
        - name: PROMETHEUS_PORT
          value: 9090
        - name: GF_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: grafana
              key: GF_SERVER_DOMAIN
        - name: FLASK_RUN_PORT
          value: 3001
        ports:
        - containerPort: 3001
          protocol: TCP
 
