apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: grafana-registry
  namespace: sodalite-services
spec:
  ports:
  - name: grafana-registry
    port: 80 
    protocol: TCP
    targetPort: 3001
  selector:
    app: grafana-registry
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}