apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: sodalite-services
spec:
  selector:
    matchLabels:
      app: alertmanager
  replicas: 1
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - image: prom/alertmanager:v0.21.0
        name: alertmanager
        ports:
        - containerPort: 9093
          protocol: TCP
        volumeMounts:
        - name: alertmanager-config
          mountPath:  /etc/alertmananger
      volumes:
      - name: alertmanager-config
        configMap:
          name: alertmanager
          items:
          - key: alertmanager.yml
            path: alertmanager.yml

 
